spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/volunteer-platform;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace